// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PokerCoach.Infrastructure.Persistence;

#nullable disable

namespace PokerCoach.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PokerCoachDbContext))]
    [Migration("20261010133042_Subscriptions")]
    partial class Subscriptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PokerCoach.Domain.Identity.EmailToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer")
                        .HasColumnName("purpose");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("token_hash")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_email_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_email_tokens_token_hash");

                    b.HasIndex("UserId", "Purpose", "CreatedAt")
                        .HasDatabaseName("ix_email_tokens_user_id_purpose_created_at");

                    b.ToTable("email_tokens", "identity");
                });

            modelBuilder.Entity("PokerCoach.Domain.Identity.ExternalIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderSubjectId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_subject_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_external_identities");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_external_identities_user_id");

                    b.HasIndex("Provider", "ProviderSubjectId")
                        .IsUnique()
                        .HasDatabaseName("ux_external_identities_provider_provider_subject_id");

                    b.ToTable("external_identities", "identity");
                });

            modelBuilder.Entity("PokerCoach.Domain.Identity.PasswordCredential", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_confirmed_at");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_attempts");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<DateTimeOffset>("PasswordChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_changed_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.HasKey("UserId")
                        .HasName("pk_password_credentials");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_password_credentials_email");

                    b.ToTable("password_credentials", "identity");
                });

            modelBuilder.Entity("PokerCoach.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("preferred_language");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", "identity");
                });

            modelBuilder.Entity("PokerCoach.Domain.Subscriptions.Subscription", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("CancelAtPeriodEnd")
                        .HasColumnType("boolean")
                        .HasColumnName("cancel_at_period_end");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("CurrentPeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_end");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("customer_id");

                    b.Property<string>("Interval")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("interval");

                    b.Property<string>("Status")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("SubscriptionId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("subscription_id");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.HasKey("UserId")
                        .HasName("pk_subscriptions");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasDatabaseName("ux_subscriptions_customer_id");

                    b.ToTable("subscriptions", "subscriptions");
                });

            modelBuilder.Entity("PokerCoach.Infrastructure.Bankroll.BankrollMovementRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_movements");

                    b.HasIndex("UserId", "OccurredAt")
                        .HasDatabaseName("ix_movements_user_id_occurred_at");

                    b.ToTable("movements", "bankroll");
                });

            modelBuilder.Entity("PokerCoach.Infrastructure.Bankroll.BankrollSettingsRecord", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Rule")
                        .HasColumnType("integer")
                        .HasColumnName("rule");

                    b.Property<DateTimeOffset>("StartedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_on");

                    b.Property<decimal>("StartingAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("starting_amount");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("pk_settings");

                    b.ToTable("settings", "bankroll");
                });

            modelBuilder.Entity("PokerCoach.Infrastructure.Coaching.CoachingReportRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("fingerprint")
                        .IsFixedLength();

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("language");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("model");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("subject");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_reports");

                    b.HasIndex("UserId", "Kind", "Subject", "Language")
                        .IsUnique()
                        .HasDatabaseName("ux_reports_user_id_kind_subject_language");

                    b.ToTable("reports", "coaching");
                });

            modelBuilder.Entity("PokerCoach.Infrastructure.Coaching.LeakExplanationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("fingerprint")
                        .IsFixedLength();

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("language");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("model");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_leak_explanations");

                    b.HasIndex("UserId", "Fingerprint")
                        .IsUnique()
                        .HasDatabaseName("ux_leak_explanations_user_id_fingerprint");

                    b.ToTable("leak_explanations", "coaching");
                });

            modelBuilder.Entity("PokerCoach.Infrastructure.Coaching.ModelUsageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CacheReadTokens")
                        .HasColumnType("integer")
                        .HasColumnName("cache_read_tokens");

                    b.Property<int>("CacheWriteTokens")
                        .HasColumnType("integer")
                        .HasColumnName("cache_write_tokens");

                    b.Property<decimal>("CostUsd")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("cost_usd");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("model");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("purpose");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_model_usage");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_model_usage_created_at");

                    b.HasIndex("UserId", "Purpose", "CreatedAt")
                        .HasDatabaseName("ix_model_usage_user_id_purpose_created_at");

                    b.ToTable("model_usage", "coaching");
                });

            modelBuilder.Entity("PokerCoach.Infrastructure.Import.ImportedFileRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<byte[]>("ContentGzip")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("content_gzip");

                    b.Property<string>("ContentSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("content_sha256")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("error_code");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<int?>("HandsAlreadyPresent")
                        .HasColumnType("integer")
                        .HasColumnName("hands_already_present");

                    b.Property<int?>("HandsImported")
                        .HasColumnType("integer")
                        .HasColumnName("hands_imported");

                    b.Property<int?>("HandsRejected")
                        .HasColumnType("integer")
                        .HasColumnName("hands_rejected");

                    b.Property<string>("Kind")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<Guid?>("PokerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("poker_account_id");

                    b.Property<string>("Rejections")
                        .HasColumnType("jsonb")
                        .HasColumnName("rejections");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_imported_files");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_imported_files_created_at")
                        .HasFilter("status IN ('pending', 'processing')");

                    b.HasIndex("PokerAccountId")
                        .HasDatabaseName("ix_imported_files_poker_account_id");

                    b.HasIndex("UserId", "BatchId")
                        .HasDatabaseName("ix_imported_files_user_id_batch_id");

                    b.HasIndex("UserId", "ContentSha256")
                        .IsUnique()
                        .HasDatabaseName("ux_imported_files_user_id_content_sha256");

                    b.ToTable("imported_files", "import", t =>
                        {
                            t.HasCheckConstraint("ck_imported_files_kind", "kind IS NULL OR kind IN ('hand_history', 'tournament_summary')");

                            t.HasCheckConstraint("ck_imported_files_status", "status IN ('pending', 'processing', 'completed', 'failed')");
                        });
                });

            modelBuilder.Entity("PokerCoach.Infrastructure.Platform.DataProtectionKeyRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_keys");

                    b.HasIndex("FriendlyName")
                        .IsUnique()
                        .HasDatabaseName("ux_data_protection_keys_friendly_name");

                    b.ToTable("data_protection_keys", "platform");
                });

            modelBuilder.Entity("PokerCoach.Infrastructure.Platform.FeatureUsageRecord", b =>
                {
                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<string>("Feature")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("feature");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Day", "Feature", "UserId")
                        .HasName("pk_feature_usage");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_feature_usage_user_id");

                    b.ToTable("feature_usage", "platform");
                });

            modelBuilder.Entity("PokerCoach.Infrastructure.Poker.HandRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long?>("Ante")
                        .HasColumnType("bigint")
                        .HasColumnName("ante");

                    b.Property<long>("BigBlind")
                        .HasColumnType("bigint")
                        .HasColumnName("big_blind");

                    b.Property<int>("ButtonSeat")
                        .HasColumnType("integer")
                        .HasColumnName("button_seat");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<string>("ExternalHandId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("external_hand_id");

                    b.Property<string>("HeroCards")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("hero_cards");

                    b.Property<int?>("HeroSeat")
                        .HasColumnType("integer")
                        .HasColumnName("hero_seat");

                    b.Property<long?>("HeroStack")
                        .HasColumnType("bigint")
                        .HasColumnName("hero_stack");

                    b.Property<Guid?>("ImportedFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("imported_file_id");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<int>("MaxSeats")
                        .HasColumnType("integer")
                        .HasColumnName("max_seats");

                    b.Property<Guid>("PokerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("poker_account_id");

                    b.Property<long>("SmallBlind")
                        .HasColumnType("bigint")
                        .HasColumnName("small_blind");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("table_name");

                    b.Property<long>("TotalPot")
                        .HasColumnType("bigint")
                        .HasColumnName("total_pot");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid")
                        .HasColumnName("tournament_id");

                    b.HasKey("Id")
                        .HasName("pk_hands");

                    b.HasIndex("ImportedFileId")
                        .HasDatabaseName("ix_hands_imported_file_id");

                    b.HasIndex("PokerAccountId", "ExternalHandId")
                        .IsUnique()
                        .HasDatabaseName("ux_hands_poker_account_id_external_hand_id");

                    b.HasIndex("TournamentId", "StartedAt")
                        .HasDatabaseName("ix_hands_tournament_id_started_at");

                    b.ToTable("hands", "poker");
                });

            modelBuilder.Entity("PokerCoach.Infrastructure.Poker.PokerAccountRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Room")
                        .HasColumnType("integer")
                        .HasColumnName("room");

                    b.Property<string>("ScreenName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("screen_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_poker_accounts");

                    b.HasIndex("UserId", "Room", "ScreenName")
                        .IsUnique()
                        .HasDatabaseName("ux_poker_accounts_user_id_room_screen_name");

                    b.ToTable("poker_accounts", "poker");
                });

            modelBuilder.Entity("PokerCoach.Infrastructure.Poker.TournamentEntryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Addons")
                        .HasColumnType("integer")
                        .HasColumnName("addons");

                    b.Property<decimal?>("BountyWinnings")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("bounty_winnings");

                    b.Property<int>("EntryNumber")
                        .HasColumnType("integer")
                        .HasColumnName("entry_number");

                    b.Property<int?>("FinishPosition")
                        .HasColumnType("integer")
                        .HasColumnName("finish_position");

                    b.Property<bool>("LateRegistration")
                        .HasColumnType("boolean")
                        .HasColumnName("late_registration");

                    b.Property<TimeSpan?>("PlayedDuration")
                        .HasColumnType("interval")
                        .HasColumnName("played_duration");

                    b.Property<decimal?>("PrizeWinnings")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("prize_winnings");

                    b.Property<int>("Rebuys")
                        .HasColumnType("integer")
                        .HasColumnName("rebuys");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid")
                        .HasColumnName("tournament_id");

                    b.HasKey("Id")
                        .HasName("pk_tournament_entries");

                    b.HasIndex("TournamentId", "EntryNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_tournament_entries_tournament_id_entry_number");

                    b.ToTable("tournament_entries", "poker");
                });

            modelBuilder.Entity("PokerCoach.Infrastructure.Poker.TournamentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("AddonCost")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("addon_cost");

                    b.Property<decimal?>("BountyBuyIn")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("bounty_buy_in");

                    b.Property<decimal?>("BuyInExcludingFee")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("buy_in_excluding_fee");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("currency");

                    b.Property<string>("ExternalTournamentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("external_tournament_id");

                    b.Property<decimal?>("Fee")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("fee");

                    b.Property<DateTimeOffset?>("FirstHandAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_hand_at");

                    b.Property<string>("FlightId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("flight_id");

                    b.Property<string>("Mode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("mode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("PokerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("poker_account_id");

                    b.Property<decimal?>("PrizePool")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("prize_pool");

                    b.Property<decimal?>("PrizePoolBuyIn")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("prize_pool_buy_in");

                    b.Property<decimal?>("RebuyCost")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("rebuy_cost");

                    b.Property<int?>("RegisteredPlayers")
                        .HasColumnType("integer")
                        .HasColumnName("registered_players");

                    b.Property<string>("Speed")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("speed");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<DateTimeOffset?>("SummaryImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("summary_imported_at");

                    b.Property<string>("TournamentType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tournament_type");

                    b.HasKey("Id")
                        .HasName("pk_tournaments");

                    b.HasIndex("PokerAccountId", "ExternalTournamentId")
                        .IsUnique()
                        .HasDatabaseName("ux_tournaments_poker_account_id_external_tournament_id");

                    b.ToTable("tournaments", "poker");
                });

            modelBuilder.Entity("PokerCoach.Infrastructure.Progress.WeeklyPlanRecord", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("date")
                        .HasColumnName("week_start");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Format")
                        .HasColumnType("integer")
                        .HasColumnName("format");

                    b.Property<string>("Priorities")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("priorities");

                    b.Property<int>("ReferenceVersion")
                        .HasColumnType("integer")
                        .HasColumnName("reference_version");

                    b.HasKey("UserId", "WeekStart")
                        .HasName("pk_weekly_plans");

                    b.ToTable("weekly_plans", "progress");
                });

            modelBuilder.Entity("PokerCoach.Infrastructure.Statistics.HandHeroFactsRecord", b =>
                {
                    b.Property<Guid>("HandId")
                        .HasColumnType("uuid")
                        .HasColumnName("hand_id");

                    b.Property<decimal?>("AllInEquity")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("all_in_equity");

                    b.Property<decimal?>("AllInExpectedNetChips")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("all_in_expected_net_chips");

                    b.Property<bool>("CbetFlop")
                        .HasColumnType("boolean")
                        .HasColumnName("cbet_flop");

                    b.Property<bool>("CbetFlopOpportunity")
                        .HasColumnType("boolean")
                        .HasColumnName("cbet_flop_opportunity");

                    b.Property<bool>("CbetTurn")
                        .HasColumnType("boolean")
                        .HasColumnName("cbet_turn");

                    b.Property<bool>("CbetTurnOpportunity")
                        .HasColumnType("boolean")
                        .HasColumnName("cbet_turn_opportunity");

                    b.Property<bool>("CheckRaiseFlop")
                        .HasColumnType("boolean")
                        .HasColumnName("check_raise_flop");

                    b.Property<bool>("CheckRaiseFlopOpportunity")
                        .HasColumnType("boolean")
                        .HasColumnName("check_raise_flop_opportunity");

                    b.Property<int>("FactsVersion")
                        .HasColumnType("integer")
                        .HasColumnName("facts_version");

                    b.Property<bool>("FoldToCbetFlop")
                        .HasColumnType("boolean")
                        .HasColumnName("fold_to_cbet_flop");

                    b.Property<bool>("FoldToCbetFlopOpportunity")
                        .HasColumnType("boolean")
                        .HasColumnName("fold_to_cbet_flop_opportunity");

                    b.Property<bool>("FoldToThreeBet")
                        .HasColumnType("boolean")
                        .HasColumnName("fold_to_three_bet");

                    b.Property<bool>("FoldToThreeBetOpportunity")
                        .HasColumnType("boolean")
                        .HasColumnName("fold_to_three_bet_opportunity");

                    b.Property<bool>("HadPreflopDecision")
                        .HasColumnType("boolean")
                        .HasColumnName("had_preflop_decision");

                    b.Property<bool>("Limp")
                        .HasColumnType("boolean")
                        .HasColumnName("limp");

                    b.Property<decimal>("NetBigBlinds")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("net_big_blinds");

                    b.Property<long>("NetChips")
                        .HasColumnType("bigint")
                        .HasColumnName("net_chips");

                    b.Property<bool>("Pfr")
                        .HasColumnType("boolean")
                        .HasColumnName("pfr");

                    b.Property<int>("PlayersDealt")
                        .HasColumnType("integer")
                        .HasColumnName("players_dealt");

                    b.Property<int?>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<int>("PostflopAggressive")
                        .HasColumnType("integer")
                        .HasColumnName("postflop_aggressive");

                    b.Property<int>("PostflopDecisions")
                        .HasColumnType("integer")
                        .HasColumnName("postflop_decisions");

                    b.Property<bool>("RaiseCbetFlop")
                        .HasColumnType("boolean")
                        .HasColumnName("raise_cbet_flop");

                    b.Property<bool>("Rfi")
                        .HasColumnType("boolean")
                        .HasColumnName("rfi");

                    b.Property<bool>("RfiOpportunity")
                        .HasColumnType("boolean")
                        .HasColumnName("rfi_opportunity");

                    b.Property<bool>("SawFlop")
                        .HasColumnType("boolean")
                        .HasColumnName("saw_flop");

                    b.Property<decimal>("StackInBigBlinds")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("stack_in_big_blinds");

                    b.Property<bool>("Steal")
                        .HasColumnType("boolean")
                        .HasColumnName("steal");

                    b.Property<bool>("StealOpportunity")
                        .HasColumnType("boolean")
                        .HasColumnName("steal_opportunity");

                    b.Property<bool>("ThreeBet")
                        .HasColumnType("boolean")
                        .HasColumnName("three_bet");

                    b.Property<bool>("ThreeBetOpportunity")
                        .HasColumnType("boolean")
                        .HasColumnName("three_bet_opportunity");

                    b.Property<bool>("Vpip")
                        .HasColumnType("boolean")
                        .HasColumnName("vpip");

                    b.Property<bool>("WentToShowdown")
                        .HasColumnType("boolean")
                        .HasColumnName("went_to_showdown");

                    b.Property<bool>("WonAtShowdown")
                        .HasColumnType("boolean")
                        .HasColumnName("won_at_showdown");

                    b.Property<bool>("WonWhenSawFlop")
                        .HasColumnType("boolean")
                        .HasColumnName("won_when_saw_flop");

                    b.HasKey("HandId")
                        .HasName("pk_hand_hero_facts");

                    b.HasIndex("FactsVersion")
                        .HasDatabaseName("ix_hand_hero_facts_facts_version");

                    b.ToTable("hand_hero_facts", "poker");
                });

            modelBuilder.Entity("PokerCoach.Infrastructure.Tournaments.TournamentCoverageRecord", b =>
                {
                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid")
                        .HasColumnName("tournament_id");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<int>("CoverageVersion")
                        .HasColumnType("integer")
                        .HasColumnName("coverage_version");

                    b.Property<bool>("EndSeen")
                        .HasColumnType("boolean")
                        .HasColumnName("end_seen");

                    b.Property<int>("EntriesSeen")
                        .HasColumnType("integer")
                        .HasColumnName("entries_seen");

                    b.Property<int?>("FirstLevel")
                        .HasColumnType("integer")
                        .HasColumnName("first_level");

                    b.Property<int>("HandCount")
                        .HasColumnType("integer")
                        .HasColumnName("hand_count");

                    b.Property<int?>("LastLevel")
                        .HasColumnType("integer")
                        .HasColumnName("last_level");

                    b.Property<int>("MissingHands")
                        .HasColumnType("integer")
                        .HasColumnName("missing_hands");

                    b.Property<int>("StackBreaks")
                        .HasColumnType("integer")
                        .HasColumnName("stack_breaks");

                    b.Property<bool?>("StartMissing")
                        .HasColumnType("boolean")
                        .HasColumnName("start_missing");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("TournamentId")
                        .HasName("pk_tournament_coverage");

                    b.ToTable("tournament_coverage", "poker");
                });

            modelBuilder.Entity("PokerCoach.Infrastructure.Training.OpeningAttemptRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Answer")
                        .HasColumnType("integer")
                        .HasColumnName("answer");

                    b.Property<int>("Band")
                        .HasColumnType("integer")
                        .HasColumnName("band");

                    b.Property<bool>("Correct")
                        .HasColumnType("boolean")
                        .HasColumnName("correct");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Format")
                        .HasColumnType("integer")
                        .HasColumnName("format");

                    b.Property<string>("Hand")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("hand");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<int?>("PushStack")
                        .HasColumnType("integer")
                        .HasColumnName("push_stack");

                    b.Property<int>("ReferenceVersion")
                        .HasColumnType("integer")
                        .HasColumnName("reference_version");

                    b.Property<int?>("Shover")
                        .HasColumnType("integer")
                        .HasColumnName("shover");

                    b.Property<Guid?>("SourceHandId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_hand_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_opening_attempts");

                    b.HasIndex("UserId", "SourceHandId")
                        .HasDatabaseName("ix_opening_attempts_user_id_source_hand_id")
                        .HasFilter("source_hand_id IS NOT NULL");

                    b.HasIndex("UserId", "Format", "CreatedAt")
                        .HasDatabaseName("ix_opening_attempts_user_id_format_created_at");

                    b.ToTable("opening_attempts", "training");
                });

            modelBuilder.Entity("PokerCoach.Domain.Identity.EmailToken", b =>
                {
                    b.HasOne("PokerCoach.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_email_tokens_users_user_id");
                });

            modelBuilder.Entity("PokerCoach.Domain.Identity.ExternalIdentity", b =>
                {
                    b.HasOne("PokerCoach.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_external_identities_users_user_id");
                });

            modelBuilder.Entity("PokerCoach.Domain.Identity.PasswordCredential", b =>
                {
                    b.HasOne("PokerCoach.Domain.Identity.User", null)
                        .WithOne()
                        .HasForeignKey("PokerCoach.Domain.Identity.PasswordCredential", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_password_credentials_users_user_id");
                });

            modelBuilder.Entity("PokerCoach.Domain.Subscriptions.Subscription", b =>
                {
                    b.HasOne("PokerCoach.Domain.Identity.User", null)
                        .WithOne()
                        .HasForeignKey("PokerCoach.Domain.Subscriptions.Subscription", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_users_user_id");
                });

            modelBuilder.Entity("PokerCoach.Infrastructure.Bankroll.BankrollMovementRecord", b =>
                {
                    b.HasOne("PokerCoach.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movements_users_user_id");
                });

            modelBuilder.Entity("PokerCoach.Infrastructure.Bankroll.BankrollSettingsRecord", b =>
                {
                    b.HasOne("PokerCoach.Domain.Identity.User", null)
                        .WithOne()
                        .HasForeignKey("PokerCoach.Infrastructure.Bankroll.BankrollSettingsRecord", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_settings_users_user_id");
                });

            modelBuilder.Entity("PokerCoach.Infrastructure.Coaching.CoachingReportRecord", b =>
                {
                    b.HasOne("PokerCoach.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reports_users_user_id");
                });

            modelBuilder.Entity("PokerCoach.Infrastructure.Coaching.LeakExplanationRecord", b =>
                {
                    b.HasOne("PokerCoach.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_leak_explanations_users_user_id");
                });

            modelBuilder.Entity("PokerCoach.Infrastructure.Coaching.ModelUsageRecord", b =>
                {
                    b.HasOne("PokerCoach.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_model_usage_users_user_id");
                });

            modelBuilder.Entity("PokerCoach.Infrastructure.Import.ImportedFileRecord", b =>
                {
                    b.HasOne("PokerCoach.Infrastructure.Poker.PokerAccountRecord", null)
                        .WithMany()
                        .HasForeignKey("PokerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_imported_files_poker_accounts_poker_account_id");

                    b.HasOne("PokerCoach.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_imported_files_users_user_id");
                });

            modelBuilder.Entity("PokerCoach.Infrastructure.Platform.FeatureUsageRecord", b =>
                {
                    b.HasOne("PokerCoach.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_feature_usage_users_user_id");
                });

            modelBuilder.Entity("PokerCoach.Infrastructure.Poker.HandRecord", b =>
                {
                    b.HasOne("PokerCoach.Infrastructure.Import.ImportedFileRecord", null)
                        .WithMany()
                        .HasForeignKey("ImportedFileId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_hands_imported_files_imported_file_id");

                    b.HasOne("PokerCoach.Infrastructure.Poker.PokerAccountRecord", null)
                        .WithMany()
                        .HasForeignKey("PokerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hands_poker_accounts_poker_account_id");

                    b.HasOne("PokerCoach.Infrastructure.Poker.TournamentRecord", null)
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hands_tournaments_tournament_id");
                });

            modelBuilder.Entity("PokerCoach.Infrastructure.Poker.PokerAccountRecord", b =>
                {
                    b.HasOne("PokerCoach.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_poker_accounts_users_user_id");
                });

            modelBuilder.Entity("PokerCoach.Infrastructure.Poker.TournamentEntryRecord", b =>
                {
                    b.HasOne("PokerCoach.Infrastructure.Poker.TournamentRecord", null)
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tournament_entries_tournaments_tournament_id");
                });

            modelBuilder.Entity("PokerCoach.Infrastructure.Poker.TournamentRecord", b =>
                {
                    b.HasOne("PokerCoach.Infrastructure.Poker.PokerAccountRecord", null)
                        .WithMany()
                        .HasForeignKey("PokerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tournaments_poker_accounts_poker_account_id");
                });

            modelBuilder.Entity("PokerCoach.Infrastructure.Progress.WeeklyPlanRecord", b =>
                {
                    b.HasOne("PokerCoach.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_weekly_plans_users_user_id");
                });

            modelBuilder.Entity("PokerCoach.Infrastructure.Statistics.HandHeroFactsRecord", b =>
                {
                    b.HasOne("PokerCoach.Infrastructure.Poker.HandRecord", null)
                        .WithOne()
                        .HasForeignKey("PokerCoach.Infrastructure.Statistics.HandHeroFactsRecord", "HandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hand_hero_facts_hands_hand_id");
                });

            modelBuilder.Entity("PokerCoach.Infrastructure.Tournaments.TournamentCoverageRecord", b =>
                {
                    b.HasOne("PokerCoach.Infrastructure.Poker.TournamentRecord", null)
                        .WithOne()
                        .HasForeignKey("PokerCoach.Infrastructure.Tournaments.TournamentCoverageRecord", "TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tournament_coverage_tournaments_tournament_id");
                });

            modelBuilder.Entity("PokerCoach.Infrastructure.Training.OpeningAttemptRecord", b =>
                {
                    b.HasOne("PokerCoach.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_opening_attempts_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
